[project]
name = "nl2sql-maf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agent-framework>=1.0.0b251016",
    "fastapi[standard]>=0.119.0",
    "uvicorn>=0.37.0",
]

[tool.uv]
prerelease = "allow"
