name: Trigger auto deployment for nl2sql-maf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nl2sql-maf-AutoDeployTrigger-ab882531-a84f-4754-9bc0-99d306243587.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NL2SQLMAF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NL2SQLMAF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NL2SQLMAF_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: 
          registryUsername: ${{ secrets.NL2SQLMAF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NL2SQLMAF_REGISTRY_PASSWORD }}
          containerAppName: nl2sql-maf
          resourceGroup: my-test-resource-group-1
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}



